---
# Ansible Galaxy Collections (latest)
collections:
  - name: prometheus.prometheus
    source: https://galaxy.ansible.com

  - name: grafana.grafana
    source: https://galaxy.ansible.com

  - name: community.general
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

# Ansible Galaxy Roles (latest)
roles:
  - name: geerlingguy.certbot
  - name: geerlingguy.nginx
